config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resources :home, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#show"

  # resources :businesses, only: [:index, :show]
  get '/businesses', to: 'businesses#index'
  get '/businesses/:id', to: 'businesses#show'
  resources :cities, only: [:index, :show]
  resources :categories, only: [:index, :show]

  namespace :admin do
    resources :categories
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ApplicationRecord
  belongs_to :city
  belongs_to :category
  validates :name, presence: true, uniqueness: true
  validates :address, presence: true
  validates :city, presence: true
  validates :zipcode, presence: true
  validates :description, presence: true
  validates :phone, presence: true
  validates :website, presence: true
  validates :category, presence: true
  validates :image_url, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :businesses
  validates :name, presence: true, uniqueness: true
  validates :image_url, presence: true

  def to_param
    slug
  end
end

app/models/city.rb
class City < ApplicationRecord
  has_many :businesses
  validates :name, presence: true, uniqueness: true
  validates :image_url, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # has_secure_password
  # validates

  enum role: [:default, :admin]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "public/404" unless current_admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index
  end

  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :current_admin?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def index
    @businesses = Business.all
  end

  def show
    @business = Business.find(params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end

  def show
    @city = City.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/categories/index.html.erb
<h1>Admin Categories</h1>

app/views/businesses/index.html.erb
<h1>All Local Businesses</h1>
<ul>
  <% @businesses.each do |business| %>
    <h3><%= link_to business.name, business_path(business) %></h3>
    <li>Address: <%= business.address%></li>
    <li>City: <%= business.city.name %></li>
    <li>Zipcode: <%= business.zipcode %></li>
    <li>Description: <%= business.description %></li>
    <li>Phone: <%= business.phone %></li>
    <li>Website: <%= business.website %></li>
    <li>Category: <%= business.category.name %></li>
    <%= image_tag business.image_url %>
  <% end %>
</ul>

app/views/businesses/show.html.erb
<ul>
  <h3><%= @business.name %></h3>
  <li>Address: <%= @business.address%></li>
  <li>City: <%= @business.city.name %></li>
  <li>Zipcode: <%= @business.zipcode %></li>
  <li>Description: <%= @business.description %></li>
  <li>Phone: <%= @business.phone %></li>
  <li>Website: <%= @business.website %></li>
  <li>Category: <%= @business.category.name %></li>
  <%= image_tag @business.image_url %>
</ul>

<%#= button_to "See All Businesses", businesses_path %>

app/views/categories/index.html.erb
<h1>All Categories</h1>
<% @categories.each do |category| %>
<li><%= link_to category.name, category_path(category) %></li>
<%= image_tag category.image_url %>
<% end %>

app/views/categories/show.html.erb
<h3><%= @category.name %></h3>
<%= image_tag @category.image_url %>

app/views/cities/index.html.erb
<h1>All Cities</h1>
<% @cities.each do |city| %>
<%= link_to city.name, city_path(city) %>
<%= image_tag city.image_url  %>
<% end %>

app/views/cities/show.html.erb
<h3><%= @city.name %></h3>
<%= image_tag @city.image_url %>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoLocal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div>
     <% if current_user %>
       Signed in as <strong><%= current_user.name %></strong>!
       <%= link_to "Sign out", signout_path, id: "sign_out" %>
     <% else %>
       <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
     <% end %>
     </div>
     <div>
    <%= yield %>
    </div>
  </body>
</html>